// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq_G-EWJ0OjgRhTkoQHfJbpAnSXWwZYhE',
    appId: '1:1058772504897:web:a91c2f702047aaedff51c0',
    messagingSenderId: '1058772504897',
    projectId: 'educast-8d2e7',
    authDomain: 'educast-8d2e7.firebaseapp.com',
    storageBucket: 'educast-8d2e7.appspot.com',
    measurementId: 'G-YP9XJWP56G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQijBctM0r40QT8kZyWSm0a37UL7gd_k',
    appId: '1:1058772504897:android:337b89742983b17aff51c0',
    messagingSenderId: '1058772504897',
    projectId: 'educast-8d2e7',
    storageBucket: 'educast-8d2e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB48GFQWJHDjokRYhBlvde1QWY-0yKom94',
    appId: '1:1058772504897:ios:1ad5f74b32df4a5bff51c0',
    messagingSenderId: '1058772504897',
    projectId: 'educast-8d2e7',
    storageBucket: 'educast-8d2e7.appspot.com',
    iosBundleId: 'com.example.educast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB48GFQWJHDjokRYhBlvde1QWY-0yKom94',
    appId: '1:1058772504897:ios:2ded001cacda7a56ff51c0',
    messagingSenderId: '1058772504897',
    projectId: 'educast-8d2e7',
    storageBucket: 'educast-8d2e7.appspot.com',
    iosBundleId: 'com.example.educast.RunnerTests',
  );
}
